import { OrderActionTypes } from '../types/orderTypes.ts';

export const getAllOrders = () => {
  return new Promise<any[]>((res) => {
    setTimeout(() => {
      res([
        {
          id: '5102fc00-66f0-4183-a1d1-e210245e838d',
          order_type: 'OFFICE_CASH',
          total: 3797,
          isViewedByAdmin: false,
          order_number: '6787156649-0',
          delivery_type: 'PICKUP',
          isPayed: false,
          user: {
            id: '8969dc27-9208-4e31-aedc-1aaf43027f24',
            name: 'Овчарова',
            lastName: 'Наталья',
            secondName: '',
            firmName: '',
            role: 'SPECIALIST',
          },
          warehouse: { city: 'Ростов-на-Дону' },
          date: '16.03.23',
        },
        {
          id: 'bde2110f-9b40-45cf-8f07-9a609c1adc2e',
          order_type: 'COURIER_CASH',
          total: 5464.8,
          isViewedByAdmin: false,
          order_number: '2087645096-1',
          delivery_type: 'DELIVERY',
          isPayed: false,
          user: {
            id: '647af982-604f-46a2-84f5-4698f1697fcc',
            name: 'Додонова',
            lastName: 'Екатерина',
            secondName: '',
            firmName: '',
            role: 'SPECIALIST',
          },
          warehouse: { city: 'Ростов-на-Дону' },
          date: '16.03.23',
        },
        {
          id: '3253042c-8a07-4758-82e0-1b8031b87970',
          order_type: 'OFFICE_TERMINAL',
          total: 1223.2,
          isViewedByAdmin: true,
          order_number: '3837858890-0',
          delivery_type: 'PICKUP',
          isPayed: false,
          user: {
            id: '9a7dab4f-b5c1-4dc9-99ba-5aaebae12b7d',
            name: 'Дижур Елена Александровна, ЧП',
            lastName: null,
            secondName: null,
            firmName: null,
            role: 'SPECIALIST',
          },
          warehouse: { city: 'Ростов-на-Дону' },
          date: '16.03.23',
        },
        {
          id: '2dac3201-dcc6-4966-9b2e-a83b469f6535',
          order_type: 'OFFICE_CASH',
          total: 1729.2,
          isViewedByAdmin: true,
          order_number: '4250815785-0',
          delivery_type: 'PICKUP',
          isPayed: false,
          user: {
            id: 'b64e888f-7cab-4f3d-8d31-c45599c0264b',
            name: 'Межгихова Виолетта ЧП',
            lastName: null,
            secondName: null,
            firmName: null,
            role: 'SPECIALIST',
          },
          warehouse: { city: 'Пятигорск' },
          date: '16.03.23',
        },
        {
          id: '4e849bb8-94f5-41a7-8eff-5028614ebfb0',
          order_type: 'OFFICE_CASH',
          total: 5793.2,
          isViewedByAdmin: true,
          order_number: '9547732992-0',
          delivery_type: 'PICKUP',
          isPayed: true,
          user: {
            id: 'd173461b-267d-44c9-a28f-126aa2d19d5c',
            name: 'Анна',
            lastName: 'Болтик',
            secondName: '',
            firmName: '',
            role: 'SPECIALIST',
          },
          warehouse: { city: 'Ростов-на-Дону' },
          date: '16.03.23',
        },
        {
          id: '30ebdb01-35b6-46b7-8338-51bae4aab6da',
          order_type: 'OFFICE_TERMINAL',
          total: 1403.6,
          isViewedByAdmin: true,
          order_number: '6423005699-1',
          delivery_type: 'PICKUP',
          isPayed: true,
          user: {
            id: 'e3319b41-a8d1-4153-b6b9-a2b0475631ea',
            name: 'Филимонова Римма Романовна, ЧП',
            lastName: null,
            secondName: null,
            firmName: null,
            role: 'SPECIALIST',
          },
          warehouse: { city: 'Ростов-на-Дону' },
          date: '16.03.23',
        },
        {
          id: '7921ebe6-6e67-422b-96c4-8be45b3e5350',
          order_type: 'OFFICE_TERMINAL',
          total: 1566.4,
          isViewedByAdmin: true,
          order_number: '3527960914-0',
          delivery_type: 'PICKUP',
          isPayed: true,
          user: {
            id: 'e3319b41-a8d1-4153-b6b9-a2b0475631ea',
            name: 'Филимонова Римма Романовна, ЧП',
            lastName: null,
            secondName: null,
            firmName: null,
            role: 'SPECIALIST',
          },
          warehouse: { city: 'Ростов-на-Дону' },
          date: '16.03.23',
        },
        {
          id: 'ddbce8f7-bcf2-4086-bb46-0b4c52b7349a',
          order_type: 'ONLINE',
          total: 2797.4,
          isViewedByAdmin: true,
          order_number: '0765694541-0',
          delivery_type: 'PICKUP',
          isPayed: true,
          user: {
            id: '287fe7e0-2ac6-455b-87ea-a741ca42a49c',
            name: 'Анастасия',
            lastName: 'Дешевич',
            secondName: '',
            firmName: '',
            role: 'SPECIALIST',
          },
          warehouse: { city: 'Краснодар' },
          date: '16.03.23',
        },
        {
          id: 'b4d05578-fa89-4c14-8c09-9dc64eebe7e9',
          order_type: 'OFFICE_CASH',
          total: 12531.6,
          isViewedByAdmin: true,
          order_number: '4243375646-0',
          delivery_type: 'PICKUP',
          isPayed: true,
          user: {
            id: '77212294-c5c4-49cb-aae1-ac868e471ffd',
            name: 'Зайнаб',
            lastName: 'Ибрагимова',
            secondName: '',
            firmName: '',
            role: 'SPECIALIST',
          },
          warehouse: { city: 'Пятигорск' },
          date: '16.03.23',
        },
        {
          id: '56353ec0-be09-43c5-acf3-9c5d7ddde129',
          order_type: 'ONLINE',
          total: 5840,
          isViewedByAdmin: true,
          order_number: '5479686512-0',
          delivery_type: 'DELIVERY',
          isPayed: true,
          user: {
            id: '57ac671f-2a60-4fe4-9621-e3ad5572ab13',
            name: 'Джанкезова Земфира Хасановна ЧП',
            lastName: null,
            secondName: null,
            firmName: null,
            role: 'SPECIALIST',
          },
          warehouse: { city: 'Пятигорск' },
          date: '16.03.23',
          count: 392,
        },
      ]);
    }, 500);
  });
};

export const editOrderName = (name: string, lastName: string, id: number) => ({
  type: OrderActionTypes.EDIT_ORDER,
  payload: {
    name: name,
    lastName: lastName,
  },
  id: id,
});

export const editOrderNumber = (order: string, id: number) => ({
  type: OrderActionTypes.EDIT_ORDER_NUMBER,
  payload: order,
  id: id,
});


