let productItems: any[] = [
  {
    id: 1,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '1%',
    checked: false,
  },
  {
    id: 2,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '2%',
    checked: false,
  },
  {
    id: 3,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '3%',
    checked: false,
  },
  {
    id: 4,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '4%',
    checked: false,
  },
  {
    id: 5,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '5%',
    checked: false,
  },
  {
    id: 6,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '6%',
    checked: false,
  },
  {
    id: 7,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '7%',
    checked: false,
  },
  {
    id: 8,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '8%',
    checked: false,
  },
  {
    id: 9,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '9%',
    checked: false,
  },
  {
    id: 10,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    checked: false,
  },
  {
    id: 11,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '11%',
    checked: false,
  },
  {
    id: 12,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '12%',
    checked: false,
  },
  {
    id: 13,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '13%',
    checked: false,
  },
  {
    id: 14,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '14%',
    checked: false,
  },
  {
    id: 15,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '15%',
    checked: false,
  },
  {
    id: 16,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '16%',
    checked: false,
  },
  {
    id: 17,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '17%',
    checked: false,
  },
  {
    id: 18,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '18%',
    checked: false,
  },
  {
    id: 19,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '19%',
    checked: false,
  },
  {
    id: 20,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '20%',
    checked: false,
  },
  {
    id: 21,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '21%',
    checked: false,
  },
];

export default productItems;
